const roadmapData = [
    // Phase 1: Foundation
    { id: 1, phase: 1, month: "1", section: "The Reasoning Layer", name: "Python Fundamentals", subtopics: ["Reading code (not just writing)", "Code comprehension & debugging", "Best practices & organization"] },
    { id: 2, phase: 1, month: "1", section: "The Reasoning Layer", name: "Pandas", subtopics: ["DataFrame operations", "Data manipulation", "Performance optimization", "Real-world data cleaning", "GroupBy & merge"] },
    { id: 3, phase: 1, month: "1", section: "The Reasoning Layer", name: "Statistics", subtopics: ["Quantifying uncertainty", "Hypothesis testing", "Probability distributions", "Sampling", "Confidence intervals", "Bayesian thinking"] },
    { id: 4, phase: 1, month: "1", section: "The Reasoning Layer", name: "Linear Algebra", subtopics: ["Geometric intuition", "Matrix operations", "Vector spaces", "Eigenvalues/eigenvectors", "SVD", "ML applications"] },
    { id: 5, phase: 1, month: "1", section: "The Reasoning Layer", name: "Calculus", subtopics: ["Derivatives & partial derivatives", "Chain rule (backprop foundation)", "Gradient intuition", "Optimization fundamentals", "Integrals for probability"] },
    { id: 6, phase: 1, month: "1", section: "The Reasoning Layer", name: "Linear Regression", subtopics: ["Mathematical foundations", "Assumptions & violations", "Failure modes", "Cost functions", "Regularization (Ridge/Lasso)", "Residual analysis"] },
    { id: 7, phase: 1, month: "2", section: "Classical ML", name: "Logistic Regression", subtopics: ["Link functions", "Binary/multi-class", "Decision boundaries", "Sigmoid derivation", "Threshold selection", "Calibration"] },
    { id: 8, phase: 1, month: "2", section: "Classical ML", name: "Decision Trees", subtopics: ["Splitting criteria (Gini, Entropy)", "Pruning", "Overfitting prevention", "Interpretability", "Feature importance"] },
    { id: 9, phase: 1, month: "2", section: "Classical ML", name: "Random Forests", subtopics: ["Ensemble methods", "Bagging", "Feature importance", "Out-of-bag error", "Feature subsampling"] },
    { id: 10, phase: 1, month: "2", section: "Classical ML", name: "Gradient Boosting (XGBoost, LightGBM, CatBoost)", subtopics: ["Sequential trees", "XGBoost", "LightGBM", "CatBoost", "Silent failures", "Hyperparameter tuning"] },
    { id: 11, phase: 1, month: "2", section: "Classical ML", name: "Unsupervised Learning", subtopics: ["K-Means", "DBSCAN", "Hierarchical clustering", "PCA", "t-SNE/UMAP", "Anomaly detection", "Silhouette score"] },
    { id: 12, phase: 1, month: "2.5", section: "Intro MLOps & Deployment", name: "Git & Version Control", subtopics: ["Repository management", "Branching", "Collaborative workflows", "Code review", ".gitignore for ML"] },
    { id: 13, phase: 1, month: "2.5", section: "Intro MLOps & Deployment", name: "Docker Fundamentals", subtopics: ["Why containerize", "Dockerfile creation", "Image optimization", "Container basics", "Docker Compose"] },
    { id: 14, phase: 1, month: "2.5", section: "Intro MLOps & Deployment", name: "Basic Model Deployment", subtopics: ["FastAPI basics", "REST APIs", "Model serving patterns", "Health checks", "Request/response schemas"] },
    { id: 15, phase: 1, month: "2.5", section: "Intro MLOps & Deployment", name: "Environment Management", subtopics: ["Virtual environments", "Dependency management (pip, poetry)", "Requirements files", "Reproducibility"] },
    { id: 16, phase: 1, month: "3", section: "Deep Learning Foundations", name: "Neural Networks from Scratch", subtopics: ["Backpropagation (NumPy)", "Gradient computation", "Activation functions", "Loss functions", "Weight initialization"] },
    { id: 17, phase: 1, month: "3", section: "Deep Learning Foundations", name: "PyTorch Fundamentals", subtopics: ["Saving/loading", "GPU management", "Autograd & computational graphs", "Tensors", "nn.Module", "Training loops"] },
    { id: 18, phase: 1, month: "3", section: "Deep Learning Foundations", name: "Optimization Algorithms", subtopics: ["SGD", "Momentum", "Adam", "Learning rate scheduling", "When to use which", "Convergence analysis"] },
    { id: 19, phase: 1, month: "3", section: "Deep Learning Foundations", name: "CNNs (Convolutional Neural Networks)", subtopics: ["Why they work for images", "Conv layers", "Pooling", "Architectures (ResNet, VGG)", "Transfer learning"] },
    { id: 20, phase: 1, month: "3", section: "Deep Learning Foundations", name: "RNNs (Recurrent Neural Networks)", subtopics: ["Sequential processing", "Vanishing/exploding gradients", "LSTM/GRU", "When to use vs Transformers", "Sequence modeling"] },
    { id: 21, phase: 1, month: "3", section: "Deep Learning Foundations", name: "Transformers", subtopics: ["Self-attention", "Positional encoding", "Multi-head attention", "Encoder-decoder", "Attention visualization"] },

    // Phase 2: Compression
    { id: 22, phase: 2, month: "4", section: "GenAI & Embeddings", name: "LLMs (Large Language Models)", subtopics: ["Pre-training", "Fine-tuning", "RLHF", "Architectures (GPT, BERT, T5, LLAMA)", "Model families"] },
    { id: 23, phase: 2, month: "4", section: "GenAI & Embeddings", name: "Vector Databases", subtopics: ["Similarity search algorithms", "HNSW", "IVF Flat search", "Performance tradeoffs", "Pinecone, Chroma, Qdrant"] },
    { id: 24, phase: 2, month: "4", section: "GenAI & Embeddings", name: "Embeddings", subtopics: ["Word embeddings (Word2Vec, GloVe)", "Sentence embeddings", "Contextual (BERT)", "Embedding geometry", "Dimensionality reduction"] },
    { id: 25, phase: 2, month: "4", section: "GenAI & Embeddings", name: "Prompt Engineering", subtopics: ["Chain of thought", "Few-shot learning", "System prompts", "Prompt optimization", "Templates", "Output formatting"] },
    { id: 26, phase: 2, month: "4", section: "GenAI & Embeddings", name: "Cost Mathematics for LLMs", subtopics: ["Token pricing", "Request cost estimation", "Scaling calculations", "Business model viability"] },
    { id: 27, phase: 2, month: "4", section: "GenAI & Embeddings", name: "RAG (Retrieval-Augmented Generation)", subtopics: ["Architecture", "Chunking strategies", "Dense vs sparse retrieval", "BM25", "Hybrid search", "Re-ranking", "Eval metrics"] },
    { id: 28, phase: 2, month: "4", section: "GenAI & Embeddings", name: "Fine-tuning LLMs", subtopics: ["When to fine-tune vs prompt", "Cost-benefit", "Data requirements", "LoRA", "Evaluation strategies"] },
    { id: 29, phase: 2, month: "4.5", section: "Advanced MLOps", name: "Experiment Tracking", subtopics: ["MLflow", "Weights & Biases", "Parameter logging", "Metric tracking", "Model versioning", "Comparison dashboards"] },
    { id: 30, phase: 2, month: "4.5", section: "Advanced MLOps", name: "Model Registry", subtopics: ["Versioning strategies", "Metadata management", "Lineage tracking", "Promotion to production", "Rollback"] },
    { id: 31, phase: 2, month: "4.5", section: "Advanced MLOps", name: "Data Versioning", subtopics: ["DVC", "Dataset tracking", "Reproducibility", "Data lineage", "Storage backends"] },
    { id: 32, phase: 2, month: "5", section: "System Design & Production ML", name: "System Design for ML", subtopics: ["Scalability", "Latency optimization", "Data pipelines", "Streaming vs batch", "Fault tolerance", "Trade-offs"] },
    { id: 33, phase: 2, month: "5", section: "System Design & Production ML", name: "Hybrid Architecture Design", subtopics: ["Rules systems", "Classic ML vs LLMs", "Tiered routing", "Cost optimization", "Request routing logic"] },
    { id: 34, phase: 2, month: "5", section: "System Design & Production ML", name: "Caching Strategies", subtopics: ["Exact match", "Semantic caching", "Fuzzy caching", "Cache hit rate", "Invalidation strategies"] },
    { id: 35, phase: 2, month: "5", section: "System Design & Production ML", name: "Fallback Chains", subtopics: ["Error handling", "Model cascading", "Graceful degradation", "Circuit breaker", "Timeout strategies"] },
    { id: 36, phase: 2, month: "5", section: "System Design & Production ML", name: "Load Balancing & Scaling", subtopics: ["Horizontal vs vertical scaling", "Load balancing", "Auto-scaling", "Traffic management", "Resource optimization"] },
    { id: 37, phase: 2, month: "5", section: "System Design & Production ML", name: "API Design for ML Systems", subtopics: ["RESTful principles", "Schemas", "Rate limiting", "Auth", "API versioning", "Batch endpoints"] },
    { id: 38, phase: 2, month: "5", section: "System Design & Production ML", name: "Monitoring & Observability", subtopics: ["Prometheus", "Grafana", "Latency (p50/p95/p99)", "Error rates", "Cost tracking", "Custom metrics"] },
    { id: 39, phase: 2, month: "5", section: "System Design & Production ML", name: "Model Drift Detection", subtopics: ["Prediction monitoring", "Feature drift", "Concept drift", "KL divergence", "Statistical tests"] },
    { id: 40, phase: 2, month: "5", section: "System Design & Production ML", name: "Logging & Debugging", subtopics: ["Structured logging", "Log aggregation", "Distributed tracing", "Production debugging", "Profiling (cProfile, PyTorch Profiler)"] },

    // Phase 3: Ownership
    { id: 41, phase: 3, month: "6-8", section: "Advanced Production", name: "CI/CD for ML", subtopics: ["Continuous integration", "Automated ML testing", "Continuous deployment", "Blue-green", "Canary releases"] },
    { id: 42, phase: 3, month: "6-8", section: "Advanced Production", name: "A/B Testing Frameworks", subtopics: ["Experiment design", "Statistical significance", "Traffic splitting", "Metrics selection", "Interpretation"] },
    { id: 43, phase: 3, month: "6-8", section: "Advanced Production", name: "Model Evaluation in Production", subtopics: ["Business vs technical metrics", "Eval frameworks", "Online vs offline", "Human-in-the-loop", "Continuous eval"] },
    { id: 44, phase: 3, month: "6-8", section: "Advanced Production", name: "Cost Optimization Advanced", subtopics: ["Model distillation", "Quantization (INT8/INT4)", "Batching", "Dynamic model selection", "Routing optimization"] },
    { id: 45, phase: 3, month: "6-8", section: "Advanced Production", name: "Feature Engineering in Production", subtopics: ["Feature stores", "Online vs offline features", "Feature monitoring", "Pipeline optimization", "Validation"] },
    { id: 46, phase: 3, month: "6-8", section: "Advanced Production", name: "Data Preprocessing Pipelines", subtopics: ["Missing data", "Outlier detection", "Data validation", "Data augmentation", "Pipeline orchestration"] },
    { id: 47, phase: 3, month: "6-8", section: "Advanced Production", name: "Model Interpretability", subtopics: ["SHAP", "LIME", "Feature importance", "Partial dependence", "Explaining to stakeholders"] },
    { id: 48, phase: 3, month: "6-8", section: "Advanced Production", name: "Incident Response & Post-mortems", subtopics: ["On-call practices", "Root cause analysis", "Post-mortem documentation", "Runbook creation", "Prevention"] },
    { id: 49, phase: 3, month: "6-8", section: "Advanced Production", name: "Security for ML Systems", subtopics: ["Model security", "API security", "Data privacy", "Adversarial attacks", "Compliance"] },
    { id: 50, phase: 3, month: "6-8", section: "Advanced Production", name: "Infrastructure as Code", subtopics: ["Terraform basics", "Cloud resource management", "Infrastructure versioning", "Automated provisioning"] },
    { id: 51, phase: 3, month: "6-8", section: "Advanced Production", name: "Batch Processing & Pipelines", subtopics: ["Batch inference", "Memory management", "Throughput vs latency", "Orchestration (Airflow, Prefect)"] },
    { id: 52, phase: 3, month: "6-8", section: "Advanced Production", name: "Streaming Data Processing", subtopics: ["Kafka fundamentals", "Stream processing patterns", "Real-time predictions", "Handling late data"] },
    { id: 53, phase: 3, month: "6-8", section: "Advanced Production", name: "Multi-model Serving", subtopics: ["Model ensembling", "Routing strategies", "Shadow deployments", "Graceful transitions"] },
    { id: 54, phase: 3, month: "6-8", section: "Advanced Production", name: "Holistic Culmination", subtopics: ["System integration", "Full-scale deployment", "Advanced production", "Career mastery"] },
];

const offerFrameworkData = [
    { id: 1, phase: 1, name: "Pick Your Starving Crowd", description: "Define your specific target market" },
    { id: 2, phase: 1, name: "Define THEIR Dream Outcome", description: "What do THEY want (not you)?" },
    { id: 3, phase: 1, name: "Map Your Value Drivers", description: "The formula determining your value" },
    { id: 4, phase: 1, name: "List Every Hiring Friction", description: "Why don't they hire you?" },
    { id: 5, phase: 1, name: "Turn Frictions into Solutions", description: "Convert friction to deliverables" },
    { id: 6, phase: 1, name: "Define Your Delivery Model", description: "How they get you" },
    { id: 7, phase: 2, name: "Trim and Stack Your Offer", description: "Keep only what matters" },
    { id: 8, phase: 2, name: "Build Your Value Stack", description: "Complete offering structure" },
    { id: 9, phase: 2, name: "Add Bonuses", description: "Extras that increase perceived value" },
    { id: 10, phase: 2, name: "Create Ethical Scarcity", description: "Make hiring time-sensitive" },
    { id: 11, phase: 3, name: "Choose Your Guarantee", description: "Risk reversal strategy" },
    { id: 12, phase: 3, name: "Name Your Offer", description: "10 variations of your intro" },
    { id: 13, phase: 3, name: "Perfect Your Value Stack Presentation", description: "Final pitch script" },
];

const worksheetData = [
    { id: 1, part: "1.1 Technical Background", text: "What is your current technical skill level?", type: "choice", options: ["Complete beginner (never coded)", "Basic programming knowledge", "Intermediate (built projects)", "Advanced (professional experience)"] },
    { id: 2, part: "1.1 Technical Background", text: "Which programming languages do you know? (Rate 1-5)", type: "rating", options: ["Python", "JavaScript", "Other"] },
    { id: 3, part: "1.1 Technical Background", text: "What is your mathematical background?", type: "choice", options: ["High school math only", "Some college-level math", "Strong math foundation", "Advanced math background"] },
    { id: 4, part: "1.1 Technical Background", text: "Have you worked with any of these before?", type: "multi", options: ["NumPy / Pandas", "SQL / Databases", "Git / GitHub", "Cloud platforms (AWS/GCP/Azure)", "Docker / Containers", "ML libraries (scikit-learn, PyTorch)", "LLMs / GenAI tools"] },
    { id: 5, part: "1.1 Technical Background", text: "Describe your most complex technical project to date (3-4 sentences)", type: "text" },
    { id: 6, part: "1.2 Time & Resource Availability", text: "How many hours per week can you REALISTICALLY commit to learning?", type: "choice", options: ["5–10 hours/week", "10–20 hours/week", "20–40 hours/week", "40+ hours/week"] },
    { id: 7, part: "1.2 Time & Resource Availability", text: "What is your timeline for getting hired?", type: "choice", options: ["3–4 months (aggressive)", "6–8 months (standard)", "9–12 months (slower pace)", "12+ months (no rush)"] },
    { id: 8, part: "1.2 Time & Resource Availability", text: "Do you have budget for paid resources?", type: "choice", options: ["No budget (free only)", "Small budget ($10–50/month)", "Moderate budget ($50–200/month)", "Flexible budget"] },
    { id: 9, part: "1.2 Time & Resource Availability", text: "Current employment status", type: "choice", options: ["Unemployed, actively job hunting", "Employed full-time, learning on side", "Student", "Freelancer / Contractor"] },
    { id: 10, part: "2.1 How You Learn Best", text: "When learning something new, you prefer:", type: "choice", options: ["Reading documentation/books deeply", "Watching video tutorials", "Building immediately and debugging", "Taking structured courses", "Mix of all approaches"] },
    { id: 11, part: "2.1 How You Learn Best", text: "Which statement resonates most with you?", type: "choice", options: ["“I need clear structure and step-by-step guidance”", "“I learn best by breaking things and fixing them”", "“I prefer understanding theory deeply before implementing”", "“I learn fastest when solving real problems”"] },
    { id: 12, part: "2.1 How You Learn Best", text: "What has stopped you from learning ML/AI before?", type: "multi", options: ["Didn’t know where to start", "Math felt too intimidating", "Started but got overwhelmed", "Tutorial hell — never built anything", "Imposter syndrome", "No clear path to getting hired"] },
    { id: 13, part: "2.1 How You Learn Best", text: "Rank your biggest learning challenges (1 = biggest, 5 = smallest)", type: "rating", options: ["Staying consistent", "Understanding complex concepts", "Knowing what to learn vs skip", "Building projects that matter", "Making time"] },
    { id: 14, part: "2.2 Constraints & Limitations", text: "Computer access level", type: "choice", options: ["Run Jupyter notebooks (minimum)", "Train small models locally", "Train medium models (GPU)", "Only have access to cloud resources"] },
    { id: 15, part: "2.2 Constraints & Limitations", text: "What’s your internet situation?", type: "choice", options: ["Reliable high-speed internet", "Moderate speed, occasional interruptions", "Limited / unstable connection"] },
    { id: 16, part: "2.2 Constraints & Limitations", text: "Are there any specific topics you want to AVOID or SKIP?", type: "text" },
    { id: 17, part: "3.1 Target Role Definition", text: "What role are you aiming for? (Check ONE primary goal)", type: "choice", options: ["ML Engineer", "AI Engineer", "Data Scientist", "MLOps Engineer", "Research Scientist", "AI Product Engineer", "Not sure yet"] },
    { id: 18, part: "3.1 Target Role Definition", text: "Which type of company do you want to work for?", type: "choice", options: ["Startups (fast-paced)", "Mid-size tech companies", "Large tech companies (FAANG)", "Non-tech building AI", "Consulting / Agency", "Remote-first companies"] },
    { id: 19, part: "3.1 Target Role Definition", text: "Geographic preference", type: "choice", options: ["Remote only (global)", "Remote, but prefer North America", "Remote, but prefer India / Asia", "Open to relocation"] },
    { id: 20, part: "3.1 Target Role Definition", text: "Salary expectations", type: "choice", options: ["Entry-level (₹5–12 LPA / $50–80K)", "Mid-level (₹12–25 LPA / $80–120K)", "Senior-level (₹25+ LPA / $120K+)", "Not concerned about salary initially"] },
    { id: 21, part: "3.2 Industry & Domain Focus", text: "Are you interested in a specific industry/domain?", type: "multi", options: ["FinTech / Finance", "HealthTech / Medical AI", "EdTech / Education", "E-commerce / Retail", "Marketing / AdTech", "Cybersecurity", "Gaming", "Climate / Sustainability", "No preference"] },
    { id: 22, part: "3.2 Industry & Domain Focus", text: "Which ML application areas excite you most? (Rank top 3)", type: "multi", options: ["NLP (chatbots, LLMs)", "Computer Vision", "Recommendation Systems", "Time Series Forecasting", "Generative AI", "Reinforcement Learning", "MLOps / Infrastructure", "Explainable AI"] },
    { id: 23, part: "3.3 Value Proposition", text: "What unique background/skills do you bring?", type: "text" },
    { id: 24, part: "3.3 Value Proposition", text: "Have you built anything publicly visible before?", type: "multi", options: ["GitHub repos with projects", "Blog posts / articles", "YouTube videos / tutorials", "Open source contributions", "Nothing yet — starting fresh"] },
    { id: 25, part: "3.3 Value Proposition", text: "On a scale of 1–10, how comfortable are you with public learning/networking?", type: "rating", options: ["Writing publicly", "Sharing failures", "Networking", "Self-promotion"] },
    { id: 26, part: "4.1 Hiring Friction", text: "Why do you think companies WOULDN’T hire you right now?", type: "multi", options: ["No degree in CS", "No prior ML work experience", "No professional software experience", "Career gap", "Age perception", "Location / timezone challenges", "Can’t prove I actually know what I claim", "Don’t have a portfolio", "Communication / English concerns"] },
    { id: 27, part: "4.1 Hiring Friction", text: "What’s your BIGGEST fear about this journey?", type: "text" },
    { id: 28, phase: "4.1 Hiring Friction", text: "Have you applied to ML/AI roles before?", type: "choice", options: ["No, never applied", "Yes, applied but no responses", "Yes, got interviews but no offers", "Yes, got offers but not right fit"] },
    { id: 29, part: "4.2 Support System", text: "Who knows about your learning goal?", type: "multi", options: ["No one — keeping it private", "Close friends / family", "Professional network", "Online community", "Accountability partner / study group"] },
    { id: 30, part: "4.2 Support System", text: "How do you handle setbacks and failures?", type: "choice", options: ["Get discouraged easily", "Need external motivation", "Push through but struggle internally", "View failures as learning opportunities", "Thrive on challenges"] },
    { id: 31, part: "4.2 Support System", text: "Do you have financial pressure to get hired quickly?", type: "choice", options: ["Yes, urgent — need income in 3–4 months", "Moderate pressure — have 6–8 months", "No pressure — can take my time", "Currently employed, no pressure"] },
    { id: 32, part: "5 Commitment", text: "Complete: “I will know this roadmap was successful when...”", type: "text" },
    { id: 33, part: "5 Commitment", text: "What will you do DIFFERENTLY this time?", type: "text" },
    { id: 34, part: "5 Commitment", text: "Which of the Five Laws of Learning resonates most with you?", type: "choice", options: ["Prediction Before Explanation", "Failure Modes Over Features", "Compression Beats Coverage", "Emotion Creates Judgment", "AI Accelerates, Humans Judge"] },
    { id: 35, part: "5 Commitment", text: "On a scale of 1–10, how committed are you to:", type: "rating", options: ["Following through for 6-8 months", "Building in public", "Outreach and networking", "Deploying real projects"] },
    { id: 36, part: "5 Commitment", text: "What’s the ONE thing that would make you quit?", type: "text" },
    { id: 37, part: "5 Commitment", text: "What’s your plan for the next 7 days?", type: "text" },
    { id: 38, part: "6 Open Questions", text: "Is there anything specific you want your roadmap to address?", type: "text" },
    { id: 39, part: "6 Open Questions", text: "Any health, personal, or situational factors?", type: "text" },
    { id: 40, part: "6 Open Questions", text: "Final thoughts, concerns, or questions:", type: "text" },
];

const resourcesData = [
    { name: "Modern AI/ML Roadmap", url: "https://docs.google.com/spreadsheets/d/1PcspNHgaVoRJKyCK9zc-uHgo0fMI96MFmK-NqGcjFNA/edit?usp=sharing", type: "spreadsheet", description: "54 topics structured by the Five Laws of Learning framework." },
    { name: "Offer Framework", url: "https://docs.google.com/spreadsheets/d/15X64hzvxffg-KBFipaKOe2bwnH-igpOBI0-0G7Ypmn0/edit?usp=sharing", type: "spreadsheet", description: "How to package yourself for hiring — positioning, outreach, and differentiation." },
    { name: "Personalization Worksheet", url: "https://docs.google.com/document/d/1HB9lc_RKNKbJwDfd5bQteJnG8mDLzYPylPnYog4CQcU/edit?usp=sharing", type: "document", description: "The foundation for your personalized AI/ML learning journey." },
    { name: "US Remote Playbook", url: "https://youtu.be/C0kwzP6Gt-4", type: "video", description: "How to land $60k-$100k roles by reaching founders directly." },
    { name: "Building Distribution", url: "https://builders.sbl.so/", type: "website", description: "Private video on building distribution as a beginner." }
];
